config/routes.rb
AutoGrader3155::Application.routes.draw do

  get "assignment_updates/index"

  root :to=> 'users#home', :via=>:get
  #devise_for :users, :skip => [:registrations] 
  devise_for :users, :skip => [:registrations] do
    get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  end
  #devise_scope :user do
   # get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  #end

  get 'users'=>'users#index'

  match 'user/:id'=>'users#show', :as=>'user', :via=>:get#, :path_names => {:show =>'Dan'}
  match 'user/:id/edit'=>'users#edit', :via=>:get, :as=>'user_edit'
  match 'user/:id/update'=>'users#update', :via=>:put, :as=>'user_update'

  match 'user/:user_id/problem/:id'=>'problems#index', :via=>:get, :as=>'submissions'
  match 'user/:user_id/problem/:id'=>'problems#submit', :via=>:post, :as=>'submit'

  match 'user/:user_id/submission/:id'=>'submissions#show', :via=>:get, :as=>'submission'
  match 'admin/user/:user_id/submission/:id'=>'submissions#download', :via=>:get, :as=>'dl'
  get "grades/summary"
  get "grades/full"

  match "announcements/:id/hide" => 'announcements#hide', as: 'hide_announcement'
  match "announcement/add" => 'assignment_updates#add', :via => :post, as: 'add_announcement'
  match "admin/assignments" => 'assignment_updates#index', :via => :get, :as => 'assignments'
  match "admin/assignments/:id/edit" => 'assignment_updates#edit', :via => :get, :as => 'edit_assignment'
  match "admin/assignments/:id" => 'assignment_updates#update', :via=>:put, as: 'update_assignment'
  match "admin/semester" => 'new_semesters#delete_db_data', via: :get, as: 'blow_up'
  match "admin/new/semester" => 'new_semesters#index', via: :get, as: 'semester'
  match "admin/new/roster"=> 'new_semesters#import_new_roster', via: :post, as: 'new_roster'
  match "admin/new/roster/example"=> 'new_semesters#csv_example', via: :get, as: 'csv_example'
  match "admin/new/reseed"=> 'new_semesters#reseed_db', via: :get, as: 'reseed'
  match "admin/assignments/hw0" => 'assignment_updates#hw0', :via=>:get, as: 'hw0'
  match "admin/assignments/hw1" => 'assignment_updates#hw1', :via=>:get, as: 'hw1'
  match "admin/assignments/hw2" => 'assignment_updates#hw2', :via=>:get, as: 'hw2'
  match "admin/assignments/hw3" => 'assignment_updates#hw3', :via=>:get, as: 'hw3'
  match "admin/assignments/hw4" => 'assignment_updates#hw4', :via=>:get, as: 'hw4'
  match 'hwsubmission/:user_id/hw2'=>'hw_submissions#hw2source', :via=>:post, :as=>'hw2source'
  match 'hwsubmission/dl/:id'=>'hw_submissions#ajax_file_dl', :via=>:post, :as=>'hw2dl'

 end

app/models/assignment_update.rb
class AssignmentUpdate < ActiveRecord::Base
  # attr_accessible :title, :body
  
end

app/controllers/assignment_updates_controller.rb
class AssignmentUpdatesController < ApplicationController
  before_filter :access_check, :check_pass
  
  def index
    @assignments = Assignment.all
  end
  
  def edit
  	@assignment = Assignment.find(params[:id])
  	@deduction = @assignment.get_deduction
  end

  def update
    if params[:commit] == 'Cancel'
      redirect_to assignments_path and return
    else
	    @assignment = Assignment.find(params[:id])
	    @deduction = Deduction.find_or_initialize_by_assignment_id(params[:id])
		  @deduction.penalty = params[:assignment][:deduction][:penalty]
      h = params[:assignment][:deduction].delete_if{|key, value| key == "penalty"}
      h=h.values.join(',').gsub(',','-') <<" 00:05:03"
		  @deduction.starts_at = DateTime.parse(h)
		  @deduction.save
    end
    if @assignment.update_attributes(params[:assignment].except(:deduction))
      redirect_to assignments_path, notice: 'Assignment was successfully updated.' 
    else
      render action: "edit", warning: "Error in Assignment Update"  
    end
  end

  def add
    a= Announcement.new
      a.message = params[:message]
      a.starts_at = Time.zone.now
      s=params[:date].values.join(',').gsub(',','-') << " 00:04:59"
      a.ends_at = s
      a.save!    
      redirect_to assignments_path
  end

  def copy_2_staging
    %x(sqlite3 #{Rails.root}/db/production.sqlite3 '.backup #{Rails.root}/db/staging.sqlite3')
  end

  def restore_from_staging
    %x(sqlite3 #{Rails.root}/db/production.sqlite3 '.restore #{Rails.root}/db/staging.sqlite3')
  end

  def hw0
    if(!Assignment.find_by_number 0)
      a0 = Assignment.create! :number=>0, :description=>"Ruby Warm-up"
      1.upto(3).each do |n|
        problem = Problem.find_or_initialize_by_number_and_assignment_id(n, a0.id)
        problem.max_score = 100
        problem.save!
      end
    end 
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.js 
      end
  end

  def hw1
    if(!Assignment.find_by_number 1) 
      a1 = Assignment.create! :number=>1, :description=>"Ruby Calisthenics"
      1.upto(6).each do |n|
        problem = Problem.find_or_initialize_by_number_and_assignment_id(n, a1.id)
        problem.max_score = 100
        problem.save!
      end
      #flash[:notice]='Successfully added hw1!'
    end 
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.js 
      end
  end

  def hw2
    if(!Assignment.find_by_number 2)
      a2 = Assignment.find_or_initialize_by_number 2
      a2.description = 'Intro to Rails'
      a2.save!
      1.upto(3).each do |n|
        problem = Problem.find_or_initialize_by_number_and_assignment_id(n, a2.id)
        problem.max_score = 100
        problem.save!
      end
    end 
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.js 
      end
  end

  def hw3
    if(!Assignment.find_by_number 3)
      a3 = Assignment.find_or_initialize_by_number 3
      a3.description = 'BDD & Cucumber'
      a3.save!
      problem = Problem.find_or_initialize_by_number_and_assignment_id(1, a3.id)
      problem.max_score = 500
      problem.save!
    end 
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.js 
      end
  end

  def hw4
    if(!Assignment.find_by_number 4)
      a4 = Assignment.find_or_initialize_by_number 4
      a4.description = 'BDD and TDD Cycle'
      a4.save!
      problem = Problem.find_or_initialize_by_number_and_assignment_id(1, a4.id)
      problem.max_score = 500
      problem.save!
    end 
      respond_to do |format|
        format.html {redirect_to assignments_path}
        format.js 
      end
  end

  private

  def access_check
    if params[:id] != current_user.id.to_s && !current_user.admin? 
      flash[:warning] = 'Permission denied'
      redirect_to root_path and return
    end
  end

end

app/helpers/assignment_updates_helper.rb
module AssignmentUpdatesHelper
end

app/views/assignment_updates/_inde.html.haml
=link_to 'Add hw0', hw0_path, {:remote=>true, :class => "btn btn-primary"}
-if Assignment.find_by_number 0
  =link_to 'Add hw1', hw1_path, {:remote=>true, :class => "btn btn-primary"}
-if Assignment.find_by_number 1
  =link_to 'Add hw2', hw2_path, {:remote=>true, :class => "btn btn-primary"}
-if Assignment.find_by_number 2
  =link_to 'Add hw3', hw3_path, {:remote=>true, :class => "btn btn-primary"}
-if Assignment.find_by_number 3
  =link_to 'Add hw4', hw4_path, {:remote=>true, :class => "btn btn-primary"}
-if Assignment.find_by_number 4
  =link_to 'Prepare For New Semester', semester_path, {:class => "btn btn-danger"}

app/views/assignment_updates/_prob.html.haml
%table{class: 'table'}
  %thead
    %tr
      %th= "HW #"
      %th= "Description"
      %th= "Time Open"
      %th= "Time Due"
      %th= "% Deduction"
      %th= ""
  %tbody#tbod
    -Assignment.all.each do |a|
      %tr
        %td=a.number
        %td=a.description
        %td=a.open_time ? a.open_time.to_formatted_s(:long) : "Not Assigned"
        %td=a.due_time ? a.due_time.to_formatted_s(:long) : "Not Assigned"
        %td=a.get_deduction
        %td
          = link_to "edit", edit_assignment_path(a), {:class => "btn btn-primary"}

app/views/assignment_updates/edit.html.erb
<h2>
  <%= "Edit Assignment #{@assignment.number} Remember to add 5hrs to desired time"%>
  </h2> 
  <h4>If you would like an assignment due 01/01/2013 at 11:59pm the correct date and time would be:
    01/01/2013 4:59am.
  </h4>
</br></br>
<%= form_for@assignment, :url => { controller: 'assignment_updates',:action => 'update'} do |f| %>
  <div class="field">
     <%= f.label :open_time, "Time Open: IN UTC " %>
     <%= f.date_select :open_time %><br />
     <%= f.time_select :open_time, :ignore_date => true %><br /><br />
  </div>
  <div class="field">
    <%= f.label :due_time, "Time Due: IN UTC" %>
    <%= f.date_select :due_time %><br />
    <%= f.time_select :due_time, :ignore_date => true %><br /><br />
  </div>
  <div class="field">
    <%= f.fields_for :deduction do |d| %>
    <%= d.label  :penalty, "% Deduction" %>
    <%= d.number_field :penalty, :value =>"#{@deduction}" %><br /><br />
    <%= d.label  :starts_at, "Starting: 00:00:01 UTC ONE DAY PRIOR" %>
    <%= d.date_select :starts_at %><br />
    <br /><br />
    <%end%>
  </div>
  <div class="action_container">
    <%= f.submit 'Submit', :class => "btn btn-primary" %>
    <%= f.submit 'Cancel', :class => "btn" %>
  </div>
  </div>
<% end %>

app/views/assignment_updates/hw0.js.erb
jQuery(function($){
        $("#mess").text('Successfully added hw0! Now edit the due date to open submissions.');
        $('#assnew').html("<%= escape_javascript(render(:partial => 'inde')) %>");
        $('#hhh').html("<%= escape_javascript(render(:partial => 'prob')) %>");
});

app/views/assignment_updates/hw1.js.erb
jQuery(function($){
        $("#mess").text('Successfully added hw1! Now edit the due date to open submissions.');
        $('#assnew').html("<%= escape_javascript(render(:partial => 'inde')) %>");
        $('#hhh').html("<%= escape_javascript(render(:partial => 'prob')) %>");
});

app/views/assignment_updates/hw2.js.erb
jQuery(function($){
        $("#mess").text('Successfully added hw2! Now edit the due date to open submissions.');
        $('#assnew').html("<%= escape_javascript(render(:partial => 'inde')) %>");
        $('#hhh').html("<%= escape_javascript(render(:partial => 'prob')) %>");
});

app/views/assignment_updates/hw3.js.erb
jQuery(function($){
        $("#mess").text('Successfully added hw3! Now edit the due date to open submissions.');
        $('#assnew').html("<%= escape_javascript(render(:partial => 'inde')) %>");
        $('#hhh').html("<%= escape_javascript(render(:partial => 'prob')) %>");
});

app/views/assignment_updates/hw4.js.erb
jQuery(function($){
        $("#mess").text('Successfully added hw4! Now edit the due date to open submissions.');
        $('#assnew').html("<%= escape_javascript(render(:partial => 'inde')) %>");
        $('#hhh').html("<%= escape_javascript(render(:partial => 'prob')) %>");
});

app/views/assignment_updates/index.html.haml
%h2 Update HW Assignments (Time in UTC so add 5hrs)
%br
  #assnew=render 'inde'
  - 2.times do
    %br
  =form_tag add_announcement_path do #, :remote => true do
    =label_tag 'Announcement'
    =text_area_tag :message, "", placeholder: "Displayed below nav links until hidden or it expires."
    %br
    =label_tag 'Ends 11:59 PM ONE DAY PRIOR'
    =select_date Time.now
    %br
    =submit_tag ' Add Global Announcement ', confirm: 'Are You sure?', :class => "btn btn-primary"

    %br
  %p

  #hhh=render 'prob'