config/routes.rb
AutoGrader3155::Application.routes.draw do

  get "assignment_updates/index"

  root :to=> 'users#home', :via=>:get
  #devise_for :users, :skip => [:registrations] 
  devise_for :users, :skip => [:registrations] do
    get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  end
  #devise_scope :user do
   # get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  #end

  get 'users'=>'users#index'

  match 'user/:id'=>'users#show', :as=>'user', :via=>:get#, :path_names => {:show =>'Dan'}
  match 'user/:id/edit'=>'users#edit', :via=>:get, :as=>'user_edit'
  match 'user/:id/update'=>'users#update', :via=>:put, :as=>'user_update'

  match 'user/:user_id/problem/:id'=>'problems#index', :via=>:get, :as=>'submissions'
  match 'user/:user_id/problem/:id'=>'problems#submit', :via=>:post, :as=>'submit'

  match 'user/:user_id/submission/:id'=>'submissions#show', :via=>:get, :as=>'submission'
  match 'admin/user/:user_id/submission/:id'=>'submissions#download', :via=>:get, :as=>'dl'
  get "grades/summary"
  get "grades/full"

  match "announcements/:id/hide" => 'announcements#hide', as: 'hide_announcement'
  match "announcement/add" => 'assignment_updates#add', :via => :post, as: 'add_announcement'
  match "admin/assignments" => 'assignment_updates#index', :via => :get, :as => 'assignments'
  match "admin/assignments/:id/edit" => 'assignment_updates#edit', :via => :get, :as => 'edit_assignment'
  match "admin/assignments/:id" => 'assignment_updates#update', :via=>:put, as: 'update_assignment'
  match "admin/semester" => 'new_semesters#delete_db_data', via: :get, as: 'blow_up'
  match "admin/new/semester" => 'new_semesters#index', via: :get, as: 'semester'
  match "admin/new/roster"=> 'new_semesters#import_new_roster', via: :post, as: 'new_roster'
  match "admin/new/roster/example"=> 'new_semesters#csv_example', via: :get, as: 'csv_example'
  match "admin/new/reseed"=> 'new_semesters#reseed_db', via: :get, as: 'reseed'
  match "admin/assignments/hw0" => 'assignment_updates#hw0', :via=>:get, as: 'hw0'
  match "admin/assignments/hw1" => 'assignment_updates#hw1', :via=>:get, as: 'hw1'
  match "admin/assignments/hw2" => 'assignment_updates#hw2', :via=>:get, as: 'hw2'
  match "admin/assignments/hw3" => 'assignment_updates#hw3', :via=>:get, as: 'hw3'
  match "admin/assignments/hw4" => 'assignment_updates#hw4', :via=>:get, as: 'hw4'
  match 'hwsubmission/:user_id/hw2'=>'hw_submissions#hw2source', :via=>:post, :as=>'hw2source'
  match 'hwsubmission/dl/:id'=>'hw_submissions#ajax_file_dl', :via=>:post, :as=>'hw2dl'

 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
   Never = Time.new(0)
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #:valadates :password_confirmation, :presence => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :username, :email, :current_password, :password, :first_name, :last_name, :student_id, :section,
    :password_confirmation, :remember_me, :admin
  attr_accessor :login

  has_many :submissions

  def submit_scores
    result = {}
    Problem.find_each do |p|
      result[p] = submissions.where(:problem_id => p.id).map(&:final_score).reject{|n| !n}.max
    end
    result #this may be where bad results are coming from
  end

  def submit_counts
    submissions.count :group => :problem_id
  end

  def full_name(current_user)
    "#{'Admin ' if current_user.admin?}#{current_user.first_name} #{current_user.last_name}"
  end

  def last_submission
    last = submissions.order(:created_at).last
    last ? last.created_at.to_time : Never
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :access_check, :except => [:home]
   before_filter :check_pass, :only => [:home, :index, :show]

  def edit
  end

  def update
    if current_user.admin? && @user == @viewer && !current_user.password_change
            
            if @user.update_with_password(params[:user]) 
              @user.password_change = true
              flash[:notice] = 'Admin Password change successful'
              sign_in @user, :bypass => true 
              params[:user].delete_if do |key, value| key =~ /password/ end
              @user.update_attributes(params[:user])
              @user.save
              if User.count < 3
                redirect_to semester_path and return
              else
                redirect_to root_path and return
              end
            else
              flash[:warning] = 'You must update your password!'
              render "edit" and return
            end
        
            
    elsif current_user.admin? && @user == @viewer && current_user.password_change
            
            if params[:user][:password].blank?
              params[:user].delete_if do |key, value| key =~ /password/ end
              flash[:notice] = 'Admin change successful, password was not updated.'
              @user.update_attributes(params[:user])
              @user.save!
            elsif @user.update_with_password(params[:user])
              flash[:notice] = 'Admin Password change successful'
              params[:user].delete_if do |key, value| key =~ /password/ end
              @user.update_attributes(params[:user])
              @user.save!
            else
              flash[:warning] = 'Update failed!'
              render "edit" and return
            end
          
        sign_in @user, :bypass => true
        redirect_to root_path and return
    
    elsif current_user.admin? && @user != @viewer && @user.update_attributes(params[:user])#.except(:current_password))
      @user.save
      #sign_in current_user, :bypass => true
      flash[:notice] = 'Update successful'
      redirect_to root_path
    elsif !current_user.admin? && @user.update_with_password(params[:user])  
      @user.update_attribute :password_change, true
      @user.save!
     # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true

      flash[:notice] = 'Password change successful'
      redirect_to root_path

    else
      flash[:warning] = 'Unsuccesful update'
      render "edit"
    end
  end

  def index
    @columns = [{:number=>0,:title=>'Last Name',:sort=>true,:field=>:last_name},
                {:number=>1,:title=>'First Name',:sort=>true,:field=>:first_name},
                #{:number=>2,:title=>'MI',:sort=>false},
                {:number=>2,:title=>'Student ID#',:sort=>true,:field=>:student_id},
                {:number=>3,:title=>'Email',:sort=>false},
                {:number=>4,:title=>'Section',:sort=>true,:field=>:section},
                {:number=>5,:title=>'Last Submission',:sort=>true,:method=>:last_submission,:dir=>'desc'},
                {:number=>6,:title=>' ',:sort=>false}, {:number=>7,:title=>' ',:sort=>false}]

    if params[:sort]
      sortcol = params[:sort].to_i
      sortcol = @columns[sortcol]
      sortdir = params[:dir] ? params[:dir].downcase : sortcol[:dir] ? sortcol[:dir] :'asc'
      sortcol[:class] = "sorted #{sortdir}"
      sortcol[:dir] = sortdir == 'desc' ? 'asc' : 'desc'
    end

    if sortcol && sortcol[:sort] && sortcol[:method]
      @users = User.all.sort_by(&sortcol[:method])
      @users = @users.reverse if sortdir == 'desc'
    elsif sortcol && sortcol[:sort] && sortcol[:field]
      ordering = "#{sortcol[:field]} #{sortdir}"
      @users = User.order(ordering).order('last_name ASC, first_name ASC')
    else
      @users = User.order('section ASC, last_name ASC, first_name ASC')
    end

    @users = @users.reject &:admin?
          respond_to do |format|
        format.js
        format.html
      end
  end

  def show
    @assignments = Assignment.order 'number DESC'
    @submits = @user.submit_counts
    @scores = @user.submit_scores
  end

  def home

    flash.keep
    redirect_to current_user.nil? ? '/users/sign_in' : ( current_user.admin? ? users_path : user_path(current_user) )
    #redirect_to current_user.admin? ? users_path : user_path(current_user);

  end

  private

  def access_check

    if params[:id] != current_user.id.to_s && !current_user.admin? 
      flash[:warning] = 'Permission denied'
      redirect_to root_path and return
    end
    @user = User.find(params[:id]) if params[:id]
    @viewer = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def last_submission_time(user)
    if user.last_submission == User::Never 
      'N/A'
    else
      local_time(user.last_submission)
    end
  end

  def column_header(col)
    if col[:sort]
      link_to col[:title], users_path(sort: col[:number], dir: col[:dir]) 
    else
      col[:title]
    end
  end
end

app/views/users/_ind.html.haml
%thead
  %tr

    %th=link_to "#{@columns[0][:title]}", users_path({sort: @columns[0][:number], dir: @columns[0][:dir]}), remote:true
    %th=link_to "#{@columns[1][:title]}", users_path({sort: @columns[1][:number], dir: @columns[1][:dir]}), remote:true
    %th=link_to "#{@columns[2][:title]}", users_path({sort: @columns[2][:number], dir: @columns[2][:dir]}),remote:true
    %th=@columns[3][:title]
    %th=link_to "#{@columns[4][:title]}", users_path({sort: @columns[4][:number], dir: @columns[4][:dir]}),remote:true 
    %th=link_to "#{@columns[5][:title]}", users_path({sort: @columns[5][:number], dir: @columns[5][:dir]}), remote:true
    %th= @columns[6][:title]

%tbody
  = render @users

app/views/users/_user.html.haml
%tr
  %td= user.last_name
  %td= user.first_name
  %td= user.student_id
  %td= mail_to user.email
  %td= user.section
  %td= last_submission_time(user)
  %td= link_to "Student View", user_path(user), {:class => "btn btn-primary"}
 	

app/views/users/edit.html.erb
<%= form_for(@user, :url => { :action => 'update'} ) do |f| %>
 <% if @user == @viewer %>
  <div class="field"><br />
     <%= f.label :password, "New Password:" %>
     <%= f.password_field :password, :autocomplete => "off"  %><br /><br />
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm New Password:' %>
    <%= f.password_field :password_confirmation %><br /><br />
  </div>
  <div class="field">
    <%= f.label :current_password, 'Current Password:' %>
    <%= f.password_field :current_password %><br /><br />
  </div>
 <% end %>
  <% if current_user.admin? %>
      <div class="field">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %><br /><br />
      </div>
      <div class="field">
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %><br /><br />
      </div>
      <div class="field">
        <%= f.label :student_id, "Student ID" %>
        <%= f.text_field :student_id %><br /><br />
        </div>
      <div class="field">
        <%= f.label :section, "Section" %>
        <%= f.text_field :section %><br /><br />
        </div>
    <% end %>
  <div class="action_container">
    <br />
    <%= f.submit "Update", :class => 'btn btn-primary' %>

  </div>
<% end %>

app/views/users/index.html.haml
%h2 Student Listing

%table#columnss{class: 'table'}
  %thead
    %tr

      %th=link_to "#{@columns[0][:title]}", users_path({sort: @columns[0][:number], dir: @columns[0][:dir]}), remote:true
      %th=link_to "#{@columns[1][:title]}", users_path({sort: @columns[1][:number], dir: @columns[1][:dir]}), remote:true
      %th=link_to "#{@columns[2][:title]}", users_path({sort: @columns[2][:number], dir: @columns[2][:dir]}),remote:true
      %th=@columns[3][:title]
      %th=link_to "#{@columns[4][:title]}", users_path({sort: @columns[4][:number], dir: @columns[4][:dir]}),remote:true 
      %th=link_to "#{@columns[5][:title]}", users_path({sort: @columns[5][:number], dir: @columns[5][:dir]}), remote:true
      %th= @columns[6][:title]
  %tbody
    = render @users
    

app/views/users/index.js.erb
jQuery(function($){
        $('#columnss').html("<%= escape_javascript(render(:partial => 'ind')) %>");
});

app/views/users/show.html.haml
- if @viewer.admin? && @viewer!=@user
  %h2= "Student View for #{@user.first_name} #{@user.last_name}"
#assignments
  - @assignments.each do |a|
    %h2.assignment= %{Homework ##{a.number}}
    %h3.description= a.description
    %h4.duedate= "Due: #{local_time a.due_time}" if a.due_time
    /hw2 addition to view source
    - if a.number == 2 && !a.due_time.nil?
      %p
      %br You must submit your source code before submitting to the grader.
      While in the directory immediately before the root directory (where you would run rails server) of your rails project run this command:
      %br
      tar -czvf hw2_{your_ninernet_id}.tar {space} hw2_rotten {then press tab and it will fill in the rest of your app name} {then hit enter}
      %br
      
      %br Make sure that you submit the most up to date version when you are finished submitting for your grades! Follow the instructions above and re-submit a newly created tar file!
      %br 
      YOU WILL NOT BE ABLE TO SUBMIT FOR GRADING UNTIL YOU HAVE DONE SO
      %br 
      THIS WILL BE USED TO HELP SOLVE WHATEVER QUESTIONS AND PROBLEMS MAY ARISE
      %br
      
      %br
      %row
        = form_tag hw2source_path(@user), {:multipart=>true, :id=>'hw2src'} do
          .errors
          = file_field_tag :hw2source, :class => 'upload'
          = submit_tag "Submit", :class => "btn btn-primary"
          %br
        -if @viewer.admin? && HwSubmission.find_by_user_id(@user)

          = form_tag hw2dl_path(@user) do
            
            =submit_tag "DL Source", :class => "btn btn-danger"
            %br
    %center
    %table{:class=> 'table' }
      %thead
        %tr
          %th Problem #
          %th Submit
          %th # Of Submissions
          %th Detailed Results
      %tbody
        - a.problems.each do |p|
          %tr
            %td= "#{p.number}"
            %td
              -if !a.due_time.nil? && (HwSubmission.find_by_user_id(@user) || a.number != 2)
                = form_tag submit_path(@user,p), {:multipart=>true, :id=>'myFile'} do
                  .errors
                  = file_field_tag :file, :class => 'upload'
                  = submit_tag "Submit", :class => "btn btn-primary"
            %td= @submits[p.id] || 0
            %td
              - if @scores[p] 
                =link_to "#{@scores[p] || 0} / #{p.max_score}", submissions_path(@user,p) 
              - else 
                ='0'
        %tr{style:"width:300px;padding:1em;margin-top:1em;background:lightgrey;"}
          %td{:colspan=>2,:style=>'color:red;text-align:left'} Totals:
          %td{style:'text-align:center;color:red'}= total_submissions @user, a
          %td{style:'text-align:center;color:red'}= "#{total_score @user, a} / #{a.max_score}"
        %tr
          %td{:colspan=>4}
            - if @viewer.admin? 
              =link_to "Edit Student Account", user_edit_path(@user, current_user), {:class => "btn btn-primary pull-right"}
              =link_to "Back To Student Listing", users_path, {:class => "btn btn-primary pull-right"}



        