config/routes.rb
AutoGrader3155::Application.routes.draw do

  get "assignment_updates/index"

  root :to=> 'users#home', :via=>:get
  #devise_for :users, :skip => [:registrations] 
  devise_for :users, :skip => [:registrations] do
    get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  end
  #devise_scope :user do
   # get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  #end

  get 'users'=>'users#index'

  match 'user/:id'=>'users#show', :as=>'user', :via=>:get#, :path_names => {:show =>'Dan'}
  match 'user/:id/edit'=>'users#edit', :via=>:get, :as=>'user_edit'
  match 'user/:id/update'=>'users#update', :via=>:put, :as=>'user_update'

  match 'user/:user_id/problem/:id'=>'problems#index', :via=>:get, :as=>'submissions'
  match 'user/:user_id/problem/:id'=>'problems#submit', :via=>:post, :as=>'submit'

  match 'user/:user_id/submission/:id'=>'submissions#show', :via=>:get, :as=>'submission'
  match 'admin/user/:user_id/submission/:id'=>'submissions#download', :via=>:get, :as=>'dl'
  get "grades/summary"
  get "grades/full"

  match "announcements/:id/hide" => 'announcements#hide', as: 'hide_announcement'
  match "announcement/add" => 'assignment_updates#add', :via => :post, as: 'add_announcement'
  match "admin/assignments" => 'assignment_updates#index', :via => :get, :as => 'assignments'
  match "admin/assignments/:id/edit" => 'assignment_updates#edit', :via => :get, :as => 'edit_assignment'
  match "admin/assignments/:id" => 'assignment_updates#update', :via=>:put, as: 'update_assignment'
  match "admin/semester" => 'new_semesters#delete_db_data', via: :get, as: 'blow_up'
  match "admin/new/semester" => 'new_semesters#index', via: :get, as: 'semester'
  match "admin/new/roster"=> 'new_semesters#import_new_roster', via: :post, as: 'new_roster'
  match "admin/new/roster/example"=> 'new_semesters#csv_example', via: :get, as: 'csv_example'
  match "admin/new/reseed"=> 'new_semesters#reseed_db', via: :get, as: 'reseed'
  match "admin/assignments/hw0" => 'assignment_updates#hw0', :via=>:get, as: 'hw0'
  match "admin/assignments/hw1" => 'assignment_updates#hw1', :via=>:get, as: 'hw1'
  match "admin/assignments/hw2" => 'assignment_updates#hw2', :via=>:get, as: 'hw2'
  match "admin/assignments/hw3" => 'assignment_updates#hw3', :via=>:get, as: 'hw3'
  match "admin/assignments/hw4" => 'assignment_updates#hw4', :via=>:get, as: 'hw4'
  match 'hwsubmission/:user_id/hw2'=>'hw_submissions#hw2source', :via=>:post, :as=>'hw2source'
  match 'hwsubmission/dl/:id'=>'hw_submissions#ajax_file_dl', :via=>:post, :as=>'hw2dl'

 end

app/controllers/new_semesters_controller.rb
require 'rake'
require 'csv'
require 'tempfile'
class NewSemestersController < ApplicationController
  before_filter :admin_check, :check_pass
  def delete_db_data year=Time.new.year, month=Time.new.month
  	begin
     %x[cd #{Rails.root} && sqlite3 #{current_db} '.backup #{hold_db}.sqlite3']
     %x[cd #{Rails.root} && rake db:drop db:create db:migrate] 
     %x[cd #{Rails.root} && rake data:add_ilson_and_admin3155]
	  rescue => ex
     Rails.logger.error "Error (new_semesters_controller#delete_db_data): #{ex}"
     flash[:warning] = "Error Destroying Data In Database #{ex}" 
    end
    if !User.find_by_username 'Admin3155'
    	User.create!(:admin=>true, :password=>'!itcs!3155!', :first_name => 'Admin', :last_name => 'Admin', :password_confirmation=>'!itcs!3155!', :username=>'admin3155', :email=>'itcsautograder@gmail.com', :section=>0, :student_id=>0)
    end
     #You are now logged in as #{current_user} and your password is  '  !itcs!3155!  '"
     if User.all.size == 2
     	flash[:warning] = "Data Successfully Destroyed, Sign in to continue."
        redirect_to semester_path
    else
    	redirect_to root_path
    end
  end

  def import_new_roster
     if !params[:file].present?
      flash[:filr] = 'Error: No file chosen for submission.'
      redirect_to semester_path and return
     elsif params[:file].original_filename !~ /.*\.csv$/i
      flash[:filr] = 'Error: File must be in CSV format. Ensure it has .csv ending!'
      redirect_to semester_path and return     	
     end
     tempfile=params[:file]
     file="#{Rails.root}/lib/tasks/rosters/#{g_time.year}-#{g_time.month}.csv"
     begin
     %x[cd #{Rails.root} && cp #{tempfile.tempfile.path} #{file} && chmod 777 #{file}]
     #sign_in(User.find(2)) :bypass => true
    #end
    #Process::detach pid
	rescue => ex
     Rails.logger.error "Error (new_semesters_controller#import_new_roster): #{ex}"
     flash[:filr] = "Error Uploading File #{ex}" 
    end
     flash[:warning] = "New Roster Successfully Imported."#You are now logged in as #{current_user} and your password is  '  !itcs!3155!  '"
     redirect_to semester_path
  end

  def csv_example
      send_file  "/#{Rails.root}/lib/tasks/rosters/0.csv", filename: 'example.csv'
  end

  def reseed_db
  	begin
  	  %x[cd #{Rails.root} && rake data:update_from_roster --trace]
    rescue => ex
     Rails.logger.error "Error (new_semesters_controller#reseed_db): #{ex}"
     flash[:warning] = "Error Updating Roster. The Problem May Stem From A Bad CSV File So Be Sure It Looks Like The Example When Opened In vim: #{ex}"
     end
     flash[:warning] = "You Should Be All Set For Next Semester!!! Make Sure Everything In The User List Is Correct, If Not: The Problem 99% Of The Time Will Be In The CSV."
     redirect_to assignments_path
  end

  private
  def g_time
  	Time.new
  end
  def hold_db year=Time.new.year, month=Time.new.month
  	"#{Rails.root}/db/pastsemesters/#{month}-#{year}#{Rails.env}"
  end

  def current_db
	"#{Rails.root}/db/#{Rails.env}.sqlite3"
  end
end

app/helpers/new_semesters_helper.rb
module NewSemestersHelper
end

app/views/new_semesters/index.html.haml
%h4 These operations should be performed in order from top to bottom if you plan to completely make the site ready for a new semester.
%br
  %br
#container_db
  %br
    -if flash[:filr].present?
      #warning.message=flash[:filr]
    = form_tag new_roster_path, {:multipart=>true, :id=>'myFile', :confirm=>'You are about to import new user data. This data will be used to seed the database.'} do
      .errors
      = file_field_tag :file, :class => 'upload', onchange: 'check_file()'
      = submit_tag "Submit", :class => "btn btn-primary"
    #warning.message FIRST: IMPORT NEW SEMESTERS ROSTER IN CSV FORMAT. BE SURE THERE ARE NO WINDOWS ENDLINES eg: (^M)
    #notice.message{:style=> 'float:center; padding-left:20px;'}
    %br
      %span The correct format for this file is :  last_name,800 #,first_name,section #,ninernet_username,uncc_email_address
    #notice.message{:style=> 'float:center; padding-left;'}
      %br
        %span Each line contains 6 entries separated by a comma (,) in the specified order, this is VERY important, click 
        %span= link_to "here", csv_example_path(:format=>'txt')#, {:class => "btn btn-primary"}
        %span for example.
%br
  %br
#container_db
  %br
  =link_to 'SECOND: RESET THE DATABASE FOR NEXT SEMESTER: THIS ACTION CANNOT BE UNDONE!', blow_up_path, {:confirm=>'You are about to delete all user data. This action cannot be undone!', :class => "btn btn-danger", :style=> 'padding-left:-10px;float:center;width:100%; height:100%;; color:white;border-style: solid; border-color:black;'}
  %p
    #notice.message{:style=> 'float:center; padding-left:20px;'}
    %br
      %span This may take a while. When done, you must sign in again. You will use the login:
      %span
      %b{:style => "BACKGROUND-COLOR: #BD362F;color:white;"}    ' admin3155 '
      %span =>
      %span
      %b{:style => "BACKGROUND-COLOR: #BD362F;color:white;"}   ' !itcs!3155! '
    %br
      %b
        #warning.message{style: 'color:#BD362F;'} DO NOT FORGET THIS USERNAME AND PASSWORD OR YOU WILL BE LOCKED OUT OF THE SYSTEM!!!
%br
  %br
#container_db
  %br
  =link_to 'FINALLY: RESEED THE DATABASE FOR THE COMING SEMESTER', reseed_path, {:confirm=>'You are about to write the imported student list to the database.', :class => "btn btn-danger", :style=> 'padding-left:-10px;float:center;width:100%; height:100%;; color:white;border-style: solid; border-color:black;'}
  %p
    #notice.message{:style=> 'float:center; padding-left:20px;'}
    %br
      %span This may take a while. When done, you must sign in again. You will use the login:
      %span
      %b{:style => "BACKGROUND-COLOR: #BD362F;color:white;"}    ' admin3155 '
      %span =>
      %span
      %b{:style => "BACKGROUND-COLOR: #BD362F;color:white;"}   ' !itcs!3155! '

:javascript
  function check_file(){
                str=document.getElementById('file').value.toUpperCase();
        suffix=".CSV";
        suffix2=".CSV";
        if(!(str.indexOf(suffix, str.length - suffix.length) !== -1)){
        alert('File type not allowed,\nAllowed file: *.csv,*.CSV');
            document.getElementById('file').value='';
        }
    }