config/routes.rb
AutoGrader3155::Application.routes.draw do

  get "assignment_updates/index"

  root :to=> 'users#home', :via=>:get
  #devise_for :users, :skip => [:registrations] 
  devise_for :users, :skip => [:registrations] do
    get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  end
  #devise_scope :user do
   # get "/users/sign_out" =>"devise/sessions#destroy", :as => :destroy_user_session
  #end

  get 'users'=>'users#index'

  match 'user/:id'=>'users#show', :as=>'user', :via=>:get#, :path_names => {:show =>'Dan'}
  match 'user/:id/edit'=>'users#edit', :via=>:get, :as=>'user_edit'
  match 'user/:id/update'=>'users#update', :via=>:put, :as=>'user_update'

  match 'user/:user_id/problem/:id'=>'problems#index', :via=>:get, :as=>'submissions'
  match 'user/:user_id/problem/:id'=>'problems#submit', :via=>:post, :as=>'submit'

  match 'user/:user_id/submission/:id'=>'submissions#show', :via=>:get, :as=>'submission'
  match 'admin/user/:user_id/submission/:id'=>'submissions#download', :via=>:get, :as=>'dl'
  get "grades/summary"
  get "grades/full"

  match "announcements/:id/hide" => 'announcements#hide', as: 'hide_announcement'
  match "announcement/add" => 'assignment_updates#add', :via => :post, as: 'add_announcement'
  match "admin/assignments" => 'assignment_updates#index', :via => :get, :as => 'assignments'
  match "admin/assignments/:id/edit" => 'assignment_updates#edit', :via => :get, :as => 'edit_assignment'
  match "admin/assignments/:id" => 'assignment_updates#update', :via=>:put, as: 'update_assignment'
  match "admin/semester" => 'new_semesters#delete_db_data', via: :get, as: 'blow_up'
  match "admin/new/semester" => 'new_semesters#index', via: :get, as: 'semester'
  match "admin/new/roster"=> 'new_semesters#import_new_roster', via: :post, as: 'new_roster'
  match "admin/new/roster/example"=> 'new_semesters#csv_example', via: :get, as: 'csv_example'
  match "admin/new/reseed"=> 'new_semesters#reseed_db', via: :get, as: 'reseed'
  match "admin/assignments/hw0" => 'assignment_updates#hw0', :via=>:get, as: 'hw0'
  match "admin/assignments/hw1" => 'assignment_updates#hw1', :via=>:get, as: 'hw1'
  match "admin/assignments/hw2" => 'assignment_updates#hw2', :via=>:get, as: 'hw2'
  match "admin/assignments/hw3" => 'assignment_updates#hw3', :via=>:get, as: 'hw3'
  match "admin/assignments/hw4" => 'assignment_updates#hw4', :via=>:get, as: 'hw4'
  match 'hwsubmission/:user_id/hw2'=>'hw_submissions#hw2source', :via=>:post, :as=>'hw2source'
  match 'hwsubmission/dl/:id'=>'hw_submissions#ajax_file_dl', :via=>:post, :as=>'hw2dl'

 end

app/views/layouts/_header.html.haml
%header#header
  = image_tag 'logo.png', id: 'logo'
  %h4.h 
    ="ITCS-3155 Autograder"
  #user_links 
    - if user_signed_in?
      %ul.usermenu{style:'margin: 0 0 10px 5px;'}
        %li.hmenu= link_to 'Assignments', user_path(current_user)
        - if current_user.admin?
          %li.hmenu= link_to 'User List', users_path
          %li.hmenu= link_to 'Grades', grades_full_path
          %li.hmenu= link_to 'Edit Assignments', assignments_path
      %ul.hmenu
        %li#username.hmenu= current_user.full_name current_user
        %li.hmenu= link_to 'Account', user_edit_path(current_user)
        %li.hmenu= link_to 'Logout', destroy_user_session_path, :method => 'delete'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link{:href=> "/favicon.ico", :rel=>"icon", :type=>"image/x-icon"}/
    /:href=>"http://www.uncc.edu/sites/all/themes/unc_charlotte/images/favicon.ico",:rel=>"shortcut icon"}
    %title ITCS 3155 Autograder
    = stylesheet_link_tag 'application', :media => "all"
    = javascript_include_tag 'application'
    /= javascript_include_tag :defaults

    =javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"
    =javascript_include_tag "http://malsup.github.com/jquery.form.js"
    = csrf_meta_tags
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-38595071-1']);
      _gaq.push(['_trackPageview']);

      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();  
  %body
    = render 'layouts/header'
    -Announcement.current(cookies.signed[:hidden_ids]).each do |announcement|
      =div_for announcement do
        =announcement.message
        - if current_user
          %a.hide=link_to "Hide", hide_announcement_path(announcement), :remote=>true
    #main
      #notice.message{:style =>'color:white'}= "h" 
      #mess
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - elsif flash[:alert]
        #warning.message= flash[:alert]
      = yield
      
    